# Generated by Django 4.1.2 on 2022-10-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo', '0002_jurnal_kampus_kelompok_ikan_delete_buku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelompok_ikan',
            name='nama_ikan',
            field=models.CharField(max_length=54),
        ),
        migrations.AlterField(
            model_name='kelompok_ikan',
            name='nama_latin',
            field=models.CharField(max_length=43),
        ),
    ]
