# Generated by Django 4.1.2 on 2022-10-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo', '0005_remove_kampus_program_studi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnal',
            name='judul',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='penulis',
            field=models.CharField(max_length=100),
        ),
    ]
