# Generated by Django 4.1.2 on 2022-10-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo', '0006_alter_jurnal_judul_alter_jurnal_penulis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jurnal',
            name='judul',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='jurnal',
            name='penulis',
            field=models.CharField(max_length=10000),
        ),
    ]
