# Generated by Django 4.1.2 on 2022-10-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_utspbo', '0007_alter_jurnal_judul_alter_jurnal_penulis'),
    ]

    operations = [
        migrations.AddField(
            model_name='jurnal',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
